# Generated by Django 6.0 on 2026-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[("Tso'er", "Tso'er"), ('Sagam', 'Sagam'), ('Segen', 'Segen'), ('Seren', 'Seren'), ('Rav-Seren', 'Rav-Seren'), ("Sa'al", "Sa'al"), ('Alam', 'Alam')], default="Tso'er", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='battalion',
            field=models.CharField(choices=[('Alon', 'Alon'), ('Gefen', 'Gefen'), ('Nahshon', 'Nahshon'), ('Brosh', 'Brosh'), ('Erez', 'Erez'), ('Hadas', 'Hadas'), ('Dolev', 'Dolev')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='platoon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BC', 'Battalion Commander'), ('PC', 'Platoon Commander'), ('TC', 'Team Commander'), ('CAD', 'Cadet')], max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
