# Generated by Django 6.0 on 2026-01-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBattalion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('battalion', models.CharField(max_length=20)),
                ('course_num', models.PositiveIntegerField()),
                ('commander', models.ForeignKey(help_text='Battalion Commander user', on_delete=django.db.models.deletion.PROTECT, related_name='commanded_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('battalion', 'course_num')},
            },
        ),
    ]
